[package]
name = "auth"
version = "0.2.0"
edition = "2021"

[dependencies]
oauth2 = "4.4.2"
db = { path = "../db" }
entities = { path = "../entities" }
rand = "0.8.5"

[dependencies.serde]
version = "1.0"
features = ["derive"]
