[package]
name = "router"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = "0.7.4"
store = { path = "../store" }
auth = { path = "../auth" }
forms = { path = "../forms" }
jsonwebtoken = "9.2.0"

[dependencies.tokio]
version = "1.28.2"
features = ["full"]
