direction: right

Frontend: {
  routes: {
    "(pages)": {
      "/[blog]"
      "/[blog]/[post]"
    }
    api: API Proxy {
      /api/auth/sign-in
      /api/auth/callback
      '/api/blogs/[blog-slug]'
      '/api/blogs/:blog-slug/entries'
      /feeds
      /forms
      /likes
      /profiles
      /uploads
      '/users/:user-id'
      /webhooks
    }
  }

  state: {
    session-store
    likes-store
  }
}

API: {
  main
  router: {
    endpoints: {
      /auth/sign-in
      /auth/callback
      '/blogs/:blog-slug'
      '/blogs/:blog-slug/entries'
      /feeds
      /forms
      /likes
      /profiles
      /uploads
      '/users/:user-id'
      /webhooks
    }
    middleware: {
      auth
    }
  }
  config
}

Lib: {
  entities: {
    user
    profile
    post
  }
  db
}

Devyctl: {
  commands: {
    create: {
      user
      profile
    }
    get
    edit
    delete
    generate
  }
}

Database

Resend
GitHub: {
  OAuth
  Repositories
  User
}
Fathom Analytics


Frontend.routes.'(pages)'.'/[blog]' -> Frontend.routes.api.'/api/blogs/[blog-slug]' -> API.router.endpoints."/blogs/:blog-slug": GET
