# This Docker Compose sets up a demo environment of Devy
version: "3"

services:
  backend:
    image: devy-backend:latest
    environment:
      DATABASE_URL: "postgres://postgres:postgres@database:5432"
      CLIENT_ID: ""
      CLIENT_SECRET: ""
      POST_AUTH_URI: "http://localhost:3000/"
      RUST_BACKTRACE: 1
    ports:
      - "8000:8000"
    build: backend

  database:
    image: devy-test-db:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    build:
      context: backend
      dockerfile: test-db.Dockerfile

