# This Docker Compose sets up a demo environment of Devy
version: "3"

services:
  backend:
    image: devy-backend:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@devy-postgres:5432
      RUST_BACKTRACE: 1
    ports:
      - "8000:8000"

  devy-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
