# This Docker Compose sets up a demo environment of Devy
version: "3"

services:
  backend:
    image: devy-backend:latest
    environment:
      DATABASE_URL: "postgres://postgres:postgres@database:5432"
      CLIENT_ID: "Iv1.9b343154e70e7b6a"
      CLIENT_SECRET: "7a58346b9915a956cbbf4fe8d1a78ad86e1c145a"
      POST_AUTH_URI: "http://localhost:3000/"
      RUST_BACKTRACE: 1
    ports:
      - "8000:8000"

  database:
    image: postgres:latest
    container_name: devy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
