# fly.toml app configuration file generated for devy on 2024-03-23T12:52:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devy'
primary_region = 'iad'

[build]
dockerfile = './api/Dockerfile'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
