[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
sqlx = { version = "0.6", features = ["postgres", "macros", "migrate", "runtime-tokio-rustls"] }

[dependencies.rocket_db_pools]
version = "=0.1.0-rc.3"
features = ["sqlx_postgres"]
