# fly.toml app configuration file generated for devy-api on 2023-07-28T22:10:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "devy-api"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
