# This Docker Compose sets up a demo environment of Devy
version: "3"

services:
  backend:
    image: devy-api:latest
    environment:
      DATABASE_URL: "postgres://postgres:postgres@database:5432"
      CLIENT_ID: ""
      CLIENT_SECRET: ""
      POST_AUTH_URI: "http://localhost:3000/"
      CALLBACK_URL: "http://localhost:8000/v1/auth/callback"
      RUST_BACKTRACE: 1
    ports:
      - "8000:8000"
    build:
      context: ..
      dockerfile: ./images/Dockerfile.api

  database:
    image: devy-test-db:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    build:
      context: ..
      dockerfile: ./images/Dockerfile.db.test
