-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.queue
(
    id uuid NOT NULL,
    createdat timestamp with time zone NOT NULL,
    updatedat timestamp with time zone NOT NULL,
    scheduledfor timestamp with time zone NOT NULL,
    failedattempts integer NOT NULL,
    status integer NOT NULL,
    message jsonb NOT NULL,
    CONSTRAINT queue_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.queue
    OWNER to postgres;

GRANT ALL ON TABLE public.queue TO anon;

GRANT ALL ON TABLE public.queue TO authenticated;

GRANT ALL ON TABLE public.queue TO postgres;

GRANT ALL ON TABLE public.queue TO service_role;
CREATE INDEX IF NOT EXISTS indexqueueonscheduledfor
    ON public.queue USING btree
    (scheduledfor ASC NULLS LAST)
    TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS indexqueueonstatus
    ON public.queue USING btree
    (status ASC NULLS LAST)
    TABLESPACE pg_default;
