-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.post
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone DEFAULT now(),
    markdown text COLLATE pg_catalog."default",
    "updatedAt" timestamp with time zone,
    title text COLLATE pg_catalog."default",
    CONSTRAINT post_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.post
    OWNER to postgres;

ALTER TABLE IF EXISTS public.post
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.post TO anon;

GRANT ALL ON TABLE public.post TO authenticated;

GRANT ALL ON TABLE public.post TO postgres;

GRANT ALL ON TABLE public.post TO service_role;

COMMENT ON TABLE public.post
    IS 'Posts published by Devy users.';
