-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.profile
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone DEFAULT now(),
    CONSTRAINT profile_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.profile
    OWNER to postgres;

GRANT ALL ON TABLE public.profile TO anon;

GRANT ALL ON TABLE public.profile TO authenticated;

GRANT ALL ON TABLE public.profile TO postgres;

GRANT ALL ON TABLE public.profile TO service_role;

ALTER TABLE IF EXISTS public.post DROP COLUMN IF EXISTS "createdAt";

ALTER TABLE IF EXISTS public.post DROP COLUMN IF EXISTS "updatedAt";

ALTER TABLE IF EXISTS public.post
    ADD COLUMN created_at timestamp with time zone DEFAULT now();

ALTER TABLE IF EXISTS public.post
    ADD COLUMN slug text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.post
    ADD COLUMN updated_at timestamp with time zone;
