create table "public"."profile" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "username" text not null default ''::text,
    "name" text,
    "user" uuid
);


alter table "public"."profile" enable row level security;

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (id);

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."profile" add constraint "profile_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) not valid;

alter table "public"."profile" validate constraint "profile_user_fkey";

create policy "Enable read access for all users"
on "public"."profile"
as permissive
for select
to public
using (true);



