create table "public"."flag" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "key" text not null default ''::text,
    "value" text not null default ''::text,
    "description" text not null default ''::text
);


alter table "public"."flag" enable row level security;

CREATE UNIQUE INDEX flag_pkey ON public.flag USING btree (id);

alter table "public"."flag" add constraint "flag_pkey" PRIMARY KEY using index "flag_pkey";

create policy "Enable read access for all users"
on "public"."flag"
as permissive
for select
to public
using (true);



