# name: Deploy API
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     name: Deploy app
#     runs-on: ubuntu-latest
#     concurrency: deploy-group
#     steps:
#       - uses: actions/checkout@v4
#       - uses: superfly/flyctl-actions/setup-flyctl@master
#       - run: cd ./backend && flyctl deploy --remote-only --config ./fly.api.toml -a devy-api
#         env:
#           FLY_API_TOKEN: ${{ secrets.FLY_API_DEPLOY_KEY }}
