name: Docker Image CI

on:
  push:
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build backend
      run: make build-backend-container
      
    - name: Run environment
      run: docker-compose up &
      
    - name: Seed database
      run: make seed-local-db
        
    - name: Run integration tests
      run: |
        cd integration/
        python3 -m pip install -r requirements.txt
        pytest
