name: Docker Image CI

on:
  push:
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup database
      run: |
        cd backend && cargo install sqlx-cli && cd -
        make create-local-db
        make migrate-local-db
        make seed-local-db

    - name: Run backend
      run: cd backend && cargo run
        
    - name: Run integration tests
      run: |
        cd integration/
        python3 -m pip install -r requirements.txt
        pytest
