name: Integration Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build backend
        run: make build-backend-container

      - name: Run backend and database
        run: docker-compose up -d

      - name: Check that the database is running
        run: docker ps

      - name: Seed database
        run: make seed-local-db

      - name: Run integration tests
        run: make run-integration-tests
